In [1]:
import numpy as np
print(np.__version__)

marks=np.array([76,32,78,46,37,85,67,43,65,74,39])   #1-d Array
print(marks,marks.size,marks.dtype,marks.ndim)

1.26.4
[76 32 78 46 37 85 67 43 65 74 39] 11 int32 1


In [3]:
import numpy as np
num=np.empty(10,dtype=int)
print(num)

for i in range(0,10):
    n=int(input("Enter a number:"))
    num[i]=n
print(num)

[-38767576     32764         0       486      1180         0       768
     32765         0         0]


Enter a number: 45
Enter a number: 54
Enter a number: 65
Enter a number: 76
Enter a number: 87
Enter a number: 8
Enter a number: 08
Enter a number: 12
Enter a number: 2
Enter a number: 34


[45 54 65 76 87  8  8 12  2 34]


In [5]:
import numpy as np 
arr1=np.array([5,6,8,9,2,3,5,8,9,3,5,6,7,1,22,11,88,144],dtype=int)
print(arr1,arr1.size,arr1.dtype)

print(f"first element is {arr1[0]}, and last element is {arr1[arr1.size-1]}")

print(arr1[0:len(arr1)-1:2])

for i in range(0,len(arr1),2):
    print(arr1[i])

[  5   6   8   9   2   3   5   8   9   3   5   6   7   1  22  11  88 144] 18 int32
first element is 5, and last element is 144
[ 5  8  2  5  9  5  7 22 88]
5
8
2
5
9
5
7
22
88


In [6]:
import numpy as np
x=np.array([1,2,3,4,5])
print(x)

[1 2 3 4 5]


In [7]:
import pandas as pd
sex=pd.Series(['Male','Male','Female','Male','Male','Female'])
ages=pd.Series([12,44,23,55,67,22,34,55,66])
print(sex)
print(ages)

0      Male
1      Male
2    Female
3      Male
4      Male
5    Female
dtype: object
0    12
1    44
2    23
3    55
4    67
5    22
6    34
7    55
8    66
dtype: int64


In [14]:
gender=np.array(sex)
age=np.array(ages)
print(gender)
print(age)

['Male' 'Male' 'Female' 'Male' 'Male' 'Female']
[12 44 23 55 67 22 34 55 66]


In [18]:
y=np.linspace(1,100,250,dtype=int)
print(y)

[  1   1   1   2   2   2   3   3   4   4   4   5   5   6   6   6   7   7
   8   8   8   9   9  10  10  10  11  11  12  12  12  13  13  14  14  14
  15  15  16  16  16  17  17  18  18  18  19  19  20  20  20  21  21  22
  22  22  23  23  24  24  24  25  25  26  26  26  27  27  28  28  28  29
  29  30  30  30  31  31  32  32  32  33  33  34  34  34  35  35  35  36
  36  37  37  37  38  38  39  39  39  40  40  41  41  41  42  42  43  43
  43  44  44  45  45  45  46  46  47  47  47  48  48  49  49  49  50  50
  51  51  51  52  52  53  53  53  54  54  55  55  55  56  56  57  57  57
  58  58  59  59  59  60  60  61  61  61  62  62  63  63  63  64  64  65
  65  65  66  66  67  67  67  68  68  68  69  69  70  70  70  71  71  72
  72  72  73  73  74  74  74  75  75  76  76  76  77  77  78  78  78  79
  79  80  80  80  81  81  82  82  82  83  83  84  84  84  85  85  86  86
  86  87  87  88  88  88  89  89  90  90  90  91  91  92  92  92  93  93
  94  94  94  95  95  96  96  96  97  97  98  98  9

In [17]:
y1=np.linspace(10,100,50,dtype=float)
print(y1)

[ 10.          11.83673469  13.67346939  15.51020408  17.34693878
  19.18367347  21.02040816  22.85714286  24.69387755  26.53061224
  28.36734694  30.20408163  32.04081633  33.87755102  35.71428571
  37.55102041  39.3877551   41.2244898   43.06122449  44.89795918
  46.73469388  48.57142857  50.40816327  52.24489796  54.08163265
  55.91836735  57.75510204  59.59183673  61.42857143  63.26530612
  65.10204082  66.93877551  68.7755102   70.6122449   72.44897959
  74.28571429  76.12244898  77.95918367  79.79591837  81.63265306
  83.46938776  85.30612245  87.14285714  88.97959184  90.81632653
  92.65306122  94.48979592  96.32653061  98.16326531 100.        ]


In [21]:
import statistics as st
import numpy as np
s=np.sum(y)
print(f"sum is {s}")
m=np.mean(y)
print(f"mean of y{m}")
md=np.median(y)
print(md)

m=np.max(y)
print(m)
x=st.mode(y)
print(x)

print(np.min(y))

sum is 12502
mean of y50.008
50.0
100
1
1


In [22]:
#3.Arange
#Return evenly spaced integer values over a given interval with some step size.
a1=np.arange(5,100,2,dtype=int)
print(a1)
print(len(a1))

[ 5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47 49 51
 53 55 57 59 61 63 65 67 69 71 73 75 77 79 81 83 85 87 89 91 93 95 97 99]
48


In [25]:
#customized function
def Gen_num(start,end,step):
    for x in range(start,end,step):
        print(x,end='')

Gen_num(3,50,3)

36912151821242730333639424548

In [26]:
#4. Uniform Samples
#Generate a random sample from a uniform distribution between lower and hogher limit values.
a2=np.random.uniform(5,10,size=100)
print(a2)

maxval=np.max(a2)
print(maxval)
print(a2.size)
print(np.min(a2))

[6.43834545 9.04908015 8.48133161 8.55421799 8.49342028 6.46828582
 8.62386717 5.09004307 7.18193926 9.56657544 6.3026919  7.39604493
 5.2144066  5.51566419 8.79344098 8.02073421 9.86072698 6.03045509
 7.30955898 8.73566722 8.2942858  9.78608918 7.53325982 7.80464808
 5.076224   9.98541295 5.53973604 7.14856918 9.22002257 7.0135178
 7.289883   6.85741225 8.99632947 6.15097263 9.46932957 5.49971728
 8.79638064 6.0168185  9.98772622 7.19684486 7.08649839 6.65995397
 8.71246827 8.30377229 8.02596841 9.48545824 6.33126252 5.21524776
 9.01069128 6.43692475 5.66505745 7.05709406 7.09238981 5.29591343
 7.23109076 5.89689683 7.12556467 5.68321873 6.69462493 5.86503952
 5.05250396 5.25648902 9.10347147 7.05058046 6.48861978 6.85970612
 7.62032189 7.92675601 6.49008229 7.24279525 8.67561287 5.46665643
 8.44293136 7.17094607 7.79267039 9.86691818 5.59292819 6.37848561
 6.23261214 6.11607732 5.29203826 7.14409554 9.06306484 8.86787883
 9.12009608 7.95139393 9.60972868 7.56949909 9.26445037 7.66130

In [27]:
data=np.random.uniform(size=50)

print(data)

[0.47970018 0.24721263 0.30237146 0.17239266 0.97755729 0.61430294
 0.19088988 0.9294852  0.72762074 0.32874975 0.59954688 0.31419063
 0.26548737 0.90059503 0.72275643 0.33038924 0.15164466 0.59307205
 0.93893879 0.08495443 0.24578408 0.60863667 0.62033688 0.19768249
 0.9077176  0.23814978 0.14644918 0.729129   0.26019851 0.07921541
 0.06455309 0.27101464 0.00454095 0.34202417 0.22639016 0.65833892
 0.35625324 0.3925485  0.03553082 0.78067176 0.07378628 0.62081345
 0.28069334 0.15111567 0.44004815 0.8508721  0.93216117 0.30559375
 0.14827561 0.76283594]


In [28]:
np.random.uniform(size=(10,5))

array([[0.78978528, 0.29035758, 0.87146538, 0.63412162, 0.9457363 ],
       [0.44816533, 0.46376455, 0.72340241, 0.91805574, 0.66256342],
       [0.29254042, 0.93618785, 0.03666148, 0.51059764, 0.87478341],
       [0.86254409, 0.00893927, 0.4543402 , 0.67614994, 0.66767349],
       [0.36333555, 0.8060007 , 0.68122234, 0.41609659, 0.36556179],
       [0.14549902, 0.45568055, 0.05512281, 0.67408567, 0.50334545],
       [0.3082903 , 0.92419638, 0.81257295, 0.92621698, 0.68843661],
       [0.19948605, 0.97643493, 0.29933484, 0.87793868, 0.08994811],
       [0.39295331, 0.28675733, 0.8149538 , 0.13731215, 0.47164385],
       [0.24693277, 0.10908151, 0.11170107, 0.97543745, 0.01139111]])

In [29]:
#5. Random.randint
#Generate n random integer samples within a range.
np.random.randint(5,10,100)

array([7, 7, 5, 6, 5, 6, 5, 8, 5, 7, 5, 9, 7, 8, 5, 9, 6, 9, 6, 6, 8, 5,
       6, 7, 6, 9, 8, 5, 8, 5, 5, 7, 6, 8, 6, 5, 5, 5, 5, 8, 7, 7, 6, 6,
       6, 6, 6, 7, 8, 7, 8, 5, 6, 8, 7, 7, 6, 7, 8, 6, 6, 8, 7, 5, 5, 9,
       6, 8, 8, 9, 5, 6, 9, 7, 5, 7, 6, 7, 5, 9, 6, 5, 6, 7, 9, 5, 9, 8,
       5, 6, 6, 7, 8, 7, 8, 8, 6, 6, 5, 5])

In [30]:
#6. Random.random
#Generate n random float samples.
np.random.random(30)

array([0.98777063, 0.62106894, 0.44518959, 0.14705441, 0.00627102,
       0.24287854, 0.77100576, 0.6232784 , 0.61785016, 0.39380377,
       0.04754304, 0.063695  , 0.5847032 , 0.77935721, 0.68555749,
       0.67327461, 0.07446745, 0.1937398 , 0.65919002, 0.83838765,
       0.3206187 , 0.41941153, 0.99855599, 0.5055173 , 0.11321035,
       0.16942433, 0.65529322, 0.31596032, 0.36657974, 0.06418552])

In [31]:
print(np.random.randint(1000,9999))

3701


In [32]:
#7. Logspace
# Generate evenly spaced numbers on a log scale.
np.logspace(0,10,5,base=10)

array([1.00000000e+00, 3.16227766e+02, 1.00000000e+05, 3.16227766e+07,
       1.00000000e+10])

In [34]:
#8. Array of zero
#np.zeros function helps to create an array of 0
np.zeros((5,3),dtype=int)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [35]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [36]:
#9. Array of ones
#np.ones function helps to create an array of 1.
np.ones((10,4),dtype=int)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [37]:
#10. Array of k Random Value
#Creates an n-dimensional array of a random value.
import numpy as np
np.full((12,4),fill_value=20)

array([[20, 20, 20, 20],
       [20, 20, 20, 20],
       [20, 20, 20, 20],
       [20, 20, 20, 20],
       [20, 20, 20, 20],
       [20, 20, 20, 20],
       [20, 20, 20, 20],
       [20, 20, 20, 20],
       [20, 20, 20, 20],
       [20, 20, 20, 20],
       [20, 20, 20, 20],
       [20, 20, 20, 20]])

In [38]:
#11. Identity Matrix
#Create an identity matrix with specified dimensions
np.identity(6,dtype=int)

array([[1, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0],
       [0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 1]])

In [43]:
#Array Operations
for i in range(1,10):
    for j in range(1,16):
        print(i*j,end='\t')
    print()

1	2	3	4	5	6	7	8	9	10	11	12	13	14	15	
2	4	6	8	10	12	14	16	18	20	22	24	26	28	30	
3	6	9	12	15	18	21	24	27	30	33	36	39	42	45	
4	8	12	16	20	24	28	32	36	40	44	48	52	56	60	
5	10	15	20	25	30	35	40	45	50	55	60	65	70	75	
6	12	18	24	30	36	42	48	54	60	66	72	78	84	90	
7	14	21	28	35	42	49	56	63	70	77	84	91	98	105	
8	16	24	32	40	48	56	64	72	80	88	96	104	112	120	
9	18	27	36	45	54	63	72	81	90	99	108	117	126	135	


In [45]:
for i in range(1,10):
    for j in range(1,10):
        if j==1 or j==9:
            print('1',end='\t')
        else:
            print('0',end='\t')
    print()

1	0	0	0	0	0	0	0	1	
1	0	0	0	0	0	0	0	1	
1	0	0	0	0	0	0	0	1	
1	0	0	0	0	0	0	0	1	
1	0	0	0	0	0	0	0	1	
1	0	0	0	0	0	0	0	1	
1	0	0	0	0	0	0	0	1	
1	0	0	0	0	0	0	0	1	
1	0	0	0	0	0	0	0	1	


In [48]:
#12. Min
arr=np.array([1,1,2,3,3,4,5,6,6,2])
np.min(arr)

1

In [49]:
#13. Max
arr=np.array([1,1,2,3,3,4,5,6,6,2])
np.max(arr)

6

In [50]:
import numpy as np
numlist=[1,3,2,4,3,5,3,4,5,4,6,5,6,2,2,1,4,1,2,4,1,5,3,2,5,5,4]
numarr=np.array(numlist)
print(numarr)
for i in range(len(numarr)):
    c=1
    for j in range(i+1,len(numarr)):

        if numarr[i]==numarr[j]:
            c=c+1
        else:
            pass
    print(numarr[i],c)

[1 3 2 4 3 5 3 4 5 4 6 5 6 2 2 1 4 1 2 4 1 5 3 2 5 5 4]
1 4
3 4
2 5
4 6
3 3
5 6
3 2
4 5
5 5
4 4
6 2
5 4
6 1
2 4
2 3
1 3
4 3
1 2
2 2
4 2
1 1
5 3
3 1
2 1
5 2
5 1
4 1


In [54]:
import numpy as np
numlist=[1,3,2,4,3,5,3,4,5,4,6,5,6,2,2,1,4,1,2,4,1,5,3,2,5,5,4]
numarr=np.array(numlist)
print(numarr)
c=0
x=int(input("Enter a number:"))
for y in numarr:
    if x==y:
        c=c+1
    else:
        pass
   
print(c)

np.unique(numarr,return_counts=True)

[1 3 2 4 3 5 3 4 5 4 6 5 6 2 2 1 4 1 2 4 1 5 3 2 5 5 4]


Enter a number: 4


6


(array([1, 2, 3, 4, 5, 6]), array([4, 5, 4, 6, 6, 2], dtype=int64))

In [55]:
#14. Unique
#Return an array with all the unique elements sorted
np.unique(arr,return_counts=True)

(array([1, 2, 3, 4, 5, 6]), array([2, 2, 2, 1, 1, 2], dtype=int64))

In [56]:
#15. Mean
#It is used to get the mean of the array.
np.mean(arr,dtype='int')

3

In [58]:
#16. Median
#Return the median value of the array.
arr=np.array([[1,2,3],[5,8,4]])
np.median(arr)

3.5

In [59]:
#17. Digitize
#Return the indices of the bins to which each value in the input array belongs.
a=np.array([-0.9,0.5,0.9,1,1.2,1.4,3.6,4.7,5.3])
bins=np.array([0,1,2,3,4,5])
np.digitize(a,bins)

array([0, 1, 1, 2, 2, 2, 4, 5, 6], dtype=int64)

In [60]:
#18. Reshape
#It is one of the most used functions of NumPy. It returns an array containing the same data with a new shape.
A=np.random.randint(15,size=(4,3))
print(A)

[[11  4  5]
 [10 11 12]
 [ 6 12  5]
 [12  2  8]]


In [61]:
A.reshape(3,4)

array([[11,  4,  5, 10],
       [11, 12,  6, 12],
       [ 5, 12,  2,  8]])

In [62]:
A.reshape(2,6)

array([[11,  4,  5, 10, 11, 12],
       [ 6, 12,  5, 12,  2,  8]])

In [63]:
A.reshape(6,2)

array([[11,  4],
       [ 5, 10],
       [11, 12],
       [ 6, 12],
       [ 5, 12],
       [ 2,  8]])

In [64]:
A.reshape(-1)

array([11,  4,  5, 10, 11, 12,  6, 12,  5, 12,  2,  8])

In [65]:
#19. Expand Dimensions
#It is used to expand the dimensions of an array. This method is useful for creating sample test data for testing a machine learning model.
arr=np.array([8,14,1,8,11,4,9,4,1,13,13,11])
z=np.expand_dims(arr,axis=0)
print(z)

[[ 8 14  1  8 11  4  9  4  1 13 13 11]]


In [66]:
x=np.expand_dims(arr,axis=1)
print(x)

[[ 8]
 [14]
 [ 1]
 [ 8]
 [11]
 [ 4]
 [ 9]
 [ 4]
 [ 1]
 [13]
 [13]
 [11]]


In [67]:
#20. Squeeze
#Reduce the dimension of an array by removing single-dimensional entrie
arr=np.array([[ 8,],[14,],[ 1,],[ 8],[11],[ 4],[ 9],[ 4],[ 1],[13],[13],[11]])
np.squeeze(arr)

array([ 8, 14,  1,  8, 11,  4,  9,  4,  1, 13, 13, 11])

In [68]:
#21. Count Non-Zero
#Count all the non-zero elements and return their count.
a=np.array([0,0,1,1,1,0])
np.count_nonzero(a)

3

In [69]:
#22. argwhere
#Find and return all the indices of non-zero elements.
a=np.array([0,0,1,1,1,0])
np.argwhere(a)

array([[2],
       [3],
       [4]], dtype=int64)

In [71]:
#23. argmax & argmin
#argmax returns the index of the max element from the array. It can be used to get the index of high probability predicted labels in multiclass image classification problems.
import numpy as np
arr=np.array([[0.12,0.64,0.19,0.05,0.9,0.2,0.01]])
m=np.argmax(arr)
n=np.argmin(arr)
print(m)
print(n)

4
6


In [2]:
#24. Sort
#Sort the array and return.
import numpy as np
arr = np.array([12,3,11,7,4,5,-90,88,44,33,23])
np.sort(arr)

array([-90,   3,   4,   5,   7,  11,  12,  23,  33,  44,  88])

In [3]:
#25. Abs
#Return the absolute values of elements inside an array. It is useful when an array contains negative values.
A = np.array([[1,-3,4],[-2,-4,3]])
np.abs(A)

array([[1, 3, 4],
       [2, 4, 3]])

In [4]:
#26. Round
#Round the float values to a specified number of decimal points.
a = np.random.uniform(12,size=(3,4))
print(a)

[[11.20709612 10.71799408  4.78620628 11.08707066]
 [ 9.68451291 11.9031446   8.06959718 11.00830603]
 [ 8.72661574 10.65068271  5.16870885 10.30560342]]


In [5]:
np.round(a,decimals=2)

array([[11.21, 10.72,  4.79, 11.09],
       [ 9.68, 11.9 ,  8.07, 11.01],
       [ 8.73, 10.65,  5.17, 10.31]])

In [6]:
np.round(a,decimals=2)

array([[11.21, 10.72,  4.79, 11.09],
       [ 9.68, 11.9 ,  8.07, 11.01],
       [ 8.73, 10.65,  5.17, 10.31]])

In [7]:
#27. Clip
#It is used to keep the values of an array within a range.
arr = np.array([0,1,-3,-4,5,6,7,2,3])
arr.clip(0,5)

array([0, 1, 0, 0, 5, 5, 5, 2, 3])

In [8]:
arr.clip(0,3)

array([0, 1, 0, 0, 3, 3, 3, 2, 3])

In [9]:
arr.clip(3,5)

array([3, 3, 3, 3, 5, 5, 5, 3, 3])

In [10]:
#Replacing Values Inside Array
#28. Where
import numpy as np
#Return elements from an array where a condition satisfies.
a = np.arange(12).reshape(4,3)
print(a)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [11]:
a[np.where(a<5)]

array([0, 1, 2, 3, 4])

In [12]:
a[np.where(a>5)]

array([ 6,  7,  8,  9, 10, 11])

In [13]:
#It can also be used to replace elements inside the panda’s data frame.

#np.where(data[feature].isnull(), 1, 0)

#Replace Null Values with 1 and other as 0

In [14]:
#29. Put
#Replaces specified elements of an array with given values.
arr = np.array([1,2,3,4,5,6])
arr

array([1, 2, 3, 4, 5, 6])

In [15]:
np.put(arr,[1,2],[60,70])
arr

array([ 1, 60, 70,  4,  5,  6])

In [16]:
#30. Copyto
#Copy the content of one array into another.
#dst: array into which values are copied.
#src: array from which values are copied.

In [17]:
arr1 = np.array([0,0,0])
arr2 = np.array([4,5,6])
print("Before arr1",arr1)
print("Before arr2",arr2)
np.copyto(arr1,arr2)
print("After arr1",arr1)
print("After arr2",arr2)

Before arr1 [0 0 0]
Before arr2 [4 5 6]
After arr1 [4 5 6]
After arr2 [4 5 6]


In [18]:
#Set Operations
#31. Retrieve Common Elements
#np.intersect1d function returns all the unique values from both arrays in a sorted manner.
ar1 = np.array([1,2,3,4,5,6])
ar2 = np.array([3,4,5,8,9,1])
np.intersect1d(ar1,ar2)

array([1, 3, 4, 5])

In [19]:
np.intersect1d(ar1,ar2,return_indices=True)

(array([1, 3, 4, 5]),
 array([0, 2, 3, 4], dtype=int64),
 array([5, 0, 1, 2], dtype=int64))

In [20]:
#32. Difference
#np.setdiff1d function returns all the unique elements from array 1 that are not present in arr2.
a = np.array([1, 7, 3, 2, 4, 1])
b = np.array([9, 2, 5, 6, 7, 8])
np.setdiff1d(a, b)

array([1, 3, 4])

In [21]:
#33. Extracts Unique Elements From Both Arrays
#setxor1d function will return all the unique values from both arrays in sorted order.
a = np.array([1, 2, 3, 4, 6])
b = np.array([1, 4, 9, 4, 36])
np.setxor1d(a,b)

array([ 2,  3,  6,  9, 36])

In [22]:
#34. Union
#union1d function will combine both arrays into one.
a = np.array([1, 2, 3, 4, 5])
b = np.array([1, 3, 5, 4, 36])
np.union1d(a,b)

array([ 1,  2,  3,  4,  5, 36])

In [23]:
#Splitting
#35. Horizontal Split
#hsplit function will split the data horizontally into n equal parts.
A = np.array([[3,4,5,2],[6,7,2,6]])
np.hsplit(A,2)    ## splits the data into two equal parts

[array([[3, 4],
        [6, 7]]),
 array([[5, 2],
        [2, 6]])]

In [24]:
np.hsplit(A,4)    ## splits the data into four equal parts

[array([[3],
        [6]]),
 array([[4],
        [7]]),
 array([[5],
        [2]]),
 array([[2],
        [6]])]

In [26]:
#36. Vertical Split
#vsplit will split the data vertically into n equal parts.
A = np.array([[3,4,5,2],[6,7,2,6]])
np.vsplit(A,2)

print(A[1],A.ndim)

[6 7 2 6] 2


In [27]:
#Stacking
#37. Horizontal Stacking
#hstack will stack appends one array at the end of another.
a = np.array([1,2,3,4,5])
b = np.array([1,4,9,16,25])
np.hstack((a,b))

array([ 1,  2,  3,  4,  5,  1,  4,  9, 16, 25])

In [ ]:
array = np.array([1, 5, 2, 8, 3])
max_value = custom_max(array)
print("Maximum value:", max_value)